AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  License: Apache-2.0
Description: 'Module 5 final lambda templete '

Resources:
  ReportLabLambdaLayer:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      Content:
        S3Bucket: "saurabhd-test"
        S3Key: "module5/reportlab-3.6.9.dist-info.zip"
      Description: "ReportLab"
      LayerName: "ReportLabLambdaLayer"
      CompatibleRuntimes:
        - "python3.8"
  
  #5.7 reort gen lambda(): getting-all-user
  ReportGenLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: "saurabhd-test"
        S3Key: "module5/alluserreport.zip"
      Description: "All user report generation python file"
      Environment:
        Variables:
          tablename: userproject
          tasktablename: ProjectTask
      FunctionName: "ReportGenModule5"
      Handler: "alluserreport.lambda_handler"
      Role: arn:aws:iam::917877325894:role/AllServicessrole
      Runtime: "python3.8"
      Timeout: 60
  #5.6 get all user lambda(): allProjTaskReport-gen
  GetAllUserProjTaskLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: "saurabhd-test"
        S3Key: "module5/allprojTask.zip"
      Description: "All user project and task"
      Environment:
        Variables:
          tablename: userproject
          tasktablename: ProjectTask
      FunctionName: "AllUserProjTask"
      Handler: "lambda_function.lambda_handler"
      Role: arn:aws:iam::917877325894:role/AllServicessrole
      Runtime: "python3.8"
  #5.5 apigatewaytest() post user
  ShowAllProjLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: "saurabhd-test"
        S3Key: "module5/jsonpostuser.zip"
      Description: "post user"
      FunctionName: "postuser"
      Handler: "lambda_function.lambda_handler"
      Role: arn:aws:iam::917877325894:role/AllServicessrole
      Runtime: "python3.8"
  #5.1 register user in cognito and update in table cognitouser()
  CognitoUserCreateTableUpdateLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: "saurabhd-test"
        S3Key: "module5/cognitouser.zip"
      Description: "Register user in cognito and update in table"
      Environment:
        Variables:
          tablename: users
          userpoolId: us-east-1_UWXOz86wh
      FunctionName: "registeruser"
      Handler: "lambda_function.lambda_handler"
      Role: arn:aws:iam::917877325894:role/AllServicessrole
      Runtime: "python3.8"
  #5.3 Event Notification myfucs3()
  EventNOtificationLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: "saurabhd-test"
        S3Key: "module5/eventnotification.zip"
      Description: "Event Notificatoin"
      FunctionName: "eventnotification"
      Handler: "lambda_function.lambda_handler"
      Role: arn:aws:iam::917877325894:role/AllServicessrole
      Runtime: "python3.8"
  #5.1 register user in cognito and update in table updateusermodule()
  UpdateDeleteUserinCognitoLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: "saurabhd-test"
        S3Key: "module5/updatedelete.zip"
      Description: "Update and delete user in cognito "
      Environment:
        Variables:
          tablename: users
          userpoolId: us-east-1_UWXOz86wh
      FunctionName: "updatedelete"
      Handler: "lambda_function.lambda_handler"
      Role: arn:aws:iam::917877325894:role/AllServicessrole
      Runtime: "python3.8"
Outputs:
  ReportGenLambdaFunctionARN:
    Value: !GetAtt "ReportGenLambdaFunction.Arn"
    Export:
      Name: "ReportGenLambdaFunctionARN::Id"
  GetAllUserProjTaskLambdaFunctionARN:
    Value: !GetAtt "GetAllUserProjTaskLambdaFunction.Arn"
    Export:
      Name: "GetAllUserProjTaskLambdaFunctionARN::Id"
  ShowAllProjLambdaFunctionARN:
    Value: !GetAtt "ShowAllProjLambdaFunction.Arn"
    Export:
      Name: "ShowAllProjLambdaFunctionARN::Id"
  CognitoUserCreateTableUpdateLambdaFunctionARN:
    Value: !GetAtt "CognitoUserCreateTableUpdateLambdaFunction.Arn"
    Export:
      Name: "CognitoUserCreateTableUpdateLambdaFunctionARN::Id"
  EventNOtificationLambdaFunctionARN:
    Value: !GetAtt "EventNOtificationLambdaFunction.Arn"
    Export:
      Name: "EventNOtificationLambdaFunctionARN::Id"
  UpdateDeleteUserinCognitoLambdaFunctionARN:
    Value: !GetAtt "UpdateDeleteUserinCognitoLambdaFunction.Arn"
    Export:
      Name: "UpdateDeleteUserinCognitoLambdaFunctionARN::Id"