Resources:
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Basic AWS Api Gateway
      StageName: Staging
  HelloLambdaFunction:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      Content:
        S3Bucket: "saurabhd-test"
        S3Key: "alluserreport.zip"
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /hello
            Method: GET