Resources:
  ReportLabLambdaLayer:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      Content:
        S3Bucket: "saurabhd-test"
        S3Key: "module5/reportlab-3.6.9.dist-info.zip"
      Description: "ReportLab"
      LayerName: "ReportLabLambdaLayer"
      CompatibleRuntimes:
        - "python3.8"
  
  GetAllUserProjTaskLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: "saurabhd-test"
        S3Key: "module5/allprojTask.zip"
      Description: "All user project and task"
      Environment:
        Variables:
          tablename: userproject
          tasktablename: ProjectTask
      FunctionName: "AllUserProjTask"
      Handler: "lambda_function.lambda_handler"
        Role: arn:aws:iam::917877325894:role/AllServicessrole
        Runtime: "python3.8"